version: '3.9'
services:
  postgres:
    container_name: task_server_psql
    image: postgres:15.4
    ports:
      - "5435:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_db
    volumes:
      - ./database-data:/var/lib/postgresql/data/

  redis:
    image: redis:7.0.12
    ports:
      - 6379:6379
